<?php if ($_SERVER['REQUEST_URI'] != '/') { header('Location: /not-found'); exit(); } ?> 
<main class="pt-20">
    <section id="carousel" class="relative mt-2" data-carousel="static">
        <div id="baseCarousel" class="relative h-96 overflow-hidden">
            <div class="hidden duration-400 ease-linear animate-pulse bg-gray-200 dark:bg-neutral-800" data-carousel-item>
                <a rel="noopener noreferrer" aria-hidden="true" tabindex="-1">
                    <img class="object-cover h-full w-full" alt="">
                </a>
            </div>
            <div class="hidden duration-400 ease-linear animate-pulse bg-gray-200 dark:bg-neutral-800" data-carousel-item>
                <a rel="noopener noreferrer" aria-hidden="true" tabindex="-1">
                    <img class="object-cover h-full w-full" alt="">
                </a>         
            </div>
            <div class="hidden duration-400 ease-linear animate-pulse bg-gray-200 dark:bg-neutral-800" data-carousel-item>
                <a rel="noopener noreferrer" aria-hidden="true" tabindex="-1">
                    <img class="object-cover h-full w-full" alt="">
                </a> 
            </div>
        </div>
        <button type="button" class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" aria-hidden="true" tabindex="-1" data-carousel-prev>
            <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60">
                <svg class="w-4 h-4 text-white dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/></svg>
            </span>
        </button>
        <button type="button" class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" aria-hidden="true" tabindex="-1" data-carousel-next>
            <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60">
                <svg class="w-4 h-4 text-white dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/></svg>          
            </span>
        </button>
    </section>
    <section aria-label="quick access" class="py-12">
        <div class="px-4 mx-auto max-w-screen-xl">
            <div class="text-center mb-6">
                <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 md:text-4xl dark:text-white">Hızlı Erişim</h1>
            </div>
            <div id="quickAccessContent" class="grid gap-2 grid grid-cols-2 lg:grid-cols-4">
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
                <div class="flex items-center rounded-lg border-l-8 border dark:border-gray-700 h-12 border-gray-400 bg-gray-100 dark:bg-neutral-800 p-4 shadow animate-pulse"></div>
            </div>
        </div>
    </section>
    <section aria-label="aday" class="bg-gray-500 bg-cover bg-center bg-no-repeat bg-blend-multiply" style="background-image: url('assets/static/img/498a6090-80e5-4214-b6ee-939ded26d017.webp');">
      <div class="relative mx-auto max-w-screen-xl px-4 py-10 xl:px-0">
        <div class="mb-6 max-w-screen-md lg:mb-0">
          <h2 class="mb-4 text-4xl font-extrabold leading-tight tracking-tight text-white md:text-5xl lg:text-6xl">Üniversite Adaylarına Merhaba!</h2>
          <p class="mb-3 font-light text-gray-300 text-sm md:text-lg">Üniversite yolculuğu heyecan vericidir ve şu anda bu yolculuğun eşiğindesiniz. Karşınıza pek çok seçenek çıkacak, bazen karmaşık görünebilir. Önemli olan kendinizi tanımak ve ilgi duyduğunuz alanları keşfetmektir.</p>
          <a href="aday" rel="noopener noreferrer" class="py-3 text-sm font-medium text-white hover:text-gray-200 underline">Aday sayfasına git</a>
        </div>
      </div>
    </section>
    <section aria-label="announcements" class="py-12">
        <div class="px-4 mx-auto max-w-screen-xl">
            <div class="flex items-center justify-between mb-8">
                <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 md:text-4xl dark:text-white">Duyurular</h1>
                <a href="announcements" rel="noopener noreferrer" class="inline-flex items-center font-medium underline underline-offset-4 text-black dark:text-gray-300 hover:no-underline">Tümünü gör</a>
            </div>
            <div id="announcementsContent" class="grid gap-8 grid sm:grid-cols-2 lg:grid-cols-3">
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-36 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
            </div>
        </div>
    </section>
    <section aria-label="news" class="py-12">
        <div class="px-4 mx-auto max-w-screen-xl">
            <div class="flex items-center justify-between mb-8">
                <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 md:text-4xl dark:text-white">Haberler</h1>
                <a href="news" rel="noopener noreferrer" class="inline-flex items-center font-medium underline underline-offset-4 text-black dark:text-gray-300 hover:no-underline">Tümünü gör</a>
            </div>
            <div id="newsContent" class="grid gap-8 grid sm:grid-cols-2 lg:grid-cols-3">
                <article class="relative">
                    <div class="flex justify-end">
                        <div class="mb-5 w-full h-56 bg-gray-200 dark:bg-neutral-800 max-w-lg animate-pulse"></div>
                    </div>
                    <div class="mb-2 w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                </article>
                <article class="relative">
                    <div class="flex justify-end">
                        <div class="mb-5 w-full h-56 bg-gray-200 dark:bg-neutral-800 max-w-lg animate-pulse"></div>
                    </div>
                    <div class="mb-2 w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                </article>
                <article class="relative">
                    <div class="flex justify-end">
                        <div class="mb-5 w-full h-56 bg-gray-200 dark:bg-neutral-800 max-w-lg animate-pulse"></div>
                    </div>
                    <div class="mb-2 w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                </article>
            </div>
        </div>
    </section>
    <section aria-label="apply" class="py-6">
        <div class="px-4 mx-auto max-w-screen-xl">
            <div class="grid items-center gap-8 lg:grid-cols-12 lg:gap-12">
                <div class="col-span-6 text-center lg:text-left">
                    <h2 class="mb-4 text-4xl font-extrabold leading-tight tracking-tight text-black dark:text-white md:text-5xl lg:text-6xl underline">Apply Nişantaşı</h2>
                    <p class="mb-4 max-w-xl text-gray-500 dark:text-gray-400">Gelecek için bir adım...</p>
                    <div class="flex items-center justify-center space-x-4 lg:justify-start">
                        <a href="apply" rel="noopener noreferrer" class="text-sm font-medium underline underline-offset-4 text-black dark:text-gray-300 hover:no-underline">Apply Nedir?</a>
                        <hr class="border-r border-gray-300 dark:border-neutral-700 h-10" />
                        <a href="apply" rel="noopener noreferrer"class="inline-flex items-center gap-1 text-sm font-medium underline underline-offset-4 text-black dark:text-gray-300 hover:no-underline">
                            Başvuru Yap 
                            <svg width="7" viewBox="0 0 6 6" height="7" aria-hidden="true"><path fill="currentColor" d="m1.252 5.547-.63-.63 3.16-3.161H1.383L1.39.891h3.887v3.89h-.87l.005-2.396z"></path></svg>
                        </a>
                    </div>
                </div>
                <div class="col-span-6">
                    <video id="applyVideoContent" class="mx-auto h-64 w-full max-w-xl sm:h-96" autoplay muted loop playsinline></video>
                </div>
            </div>
        </div>
    </section>
    <section aria-label="events" class="py-12">
        <div class="px-4 mx-auto max-w-screen-xl">
            <div class="flex items-center justify-between mb-8">
                <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 md:text-4xl dark:text-white">Etkinlikler</h1>
                <a href="events" rel="noopener noreferrer" class="inline-flex items-center font-medium underline underline-offset-4 text-black dark:text-gray-300 hover:no-underline">Tümünü gör</a>
            </div>
            <div id="eventsContent" class="grid gap-8 grid sm:grid-cols-2 lg:grid-cols-3">
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white dark:text-black animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white dark:text-black animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white dark:text-black animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white dark:text-black animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white dark:text-black animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
                <article class="flex">
                    <div class="mr-4 h-16 w-16 flex-shrink-0 overflow-hidden bg-gray-200 dark:bg-neutral-800 text-white dark:text-black animate-pulse"></div>
                    <div class="space-y-2 w-full">
                        <div class="w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                        <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    </div>
                </article>
            </div>
        </div>
    </section>
    <section aria-label="research" class="py-12">
        <div class="px-4 mx-auto max-w-screen-xl">
            <div class="flex items-center justify-between mb-8">
                <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 md:text-4xl dark:text-white">Araştırmalar</h1>
                <a href="research" rel="noopener noreferrer" class="inline-flex items-center font-medium underline underline-offset-4 text-black dark:text-gray-300 hover:no-underline">Tümünü gör</a>
            </div>
            <div id="researchContent" class="grid gap-8 grid sm:grid-cols-2 lg:grid-cols-3">
                <article class="relative">
                    <div class="flex justify-end">
                        <div class="mb-5 w-full h-56 bg-gray-200 dark:bg-neutral-800 max-w-lg animate-pulse"></div>
                    </div>
                    <div class="mb-2 w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                </article>
                <article class="relative">
                    <div class="flex justify-end">
                        <div class="mb-5 w-full h-56 bg-gray-200 dark:bg-neutral-800 max-w-lg animate-pulse"></div>
                    </div>
                    <div class="mb-2 w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                </article>
                <article class="relative">
                    <div class="flex justify-end">
                        <div class="mb-5 w-full h-56 bg-gray-200 dark:bg-neutral-800 max-w-lg animate-pulse"></div>
                    </div>
                    <div class="mb-2 w-full h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                    <div class="w-16 h-2 bg-gray-200 dark:bg-neutral-800 rounded-full animate-pulse"></div>
                </article>
            </div>
        </div>
    </section>
    <section aria-label="brands" class="py-12">
        <div class="gap-8 py-10 px-4 mx-auto max-w-screen-xl sm:gap-16 lg:gap-20 md:px-6">
            <div class="text-gray-500 sm:text-lg dark:text-gray-400 mb-8 text-center">
                <h1 class="mb-4 text-3xl font-extrabold tracking-tight text-gray-900 md:text-4xl dark:text-white">Anlaşmalı Kurumlar</h1>
                <p class="font-light lg:text-xl">Üniversitemiz, çeşitli kurumlarla işbirliği içinde çalışarak öğrencilere ve personeline daha geniş imkanlar sunmaktadır.</p>
            </div>
            <section class="w-full max-w-5xl mx-auto px-4 md:px-6">
                <div class="text-center">
                    <div x-data="{}" x-init="$nextTick(() => {let ul = $refs.logos; ul.insertAdjacentHTML('afterend', ul.outerHTML); ul.nextSibling.setAttribute('aria-hidden', 'true');})" class="w-full inline-flex flex-nowrap overflow-hidden [mask-image:_linear-gradient(to_right,transparent_0,_black_128px,_black_calc(100%-128px),transparent_100%)]" >
                        <ul id="contractedBrandsLogos" x-ref="logos" class="flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
                            <li class="w-32 h-5 animate-pulse bg-gray-200 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-200 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-200 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-200 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-200 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-200 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-200 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-200 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-400 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-400 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-400 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-400 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-400 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-400 dark:bg-neutral-800"></li>
                            <li class="w-32 h-5 animate-pulse bg-gray-400 dark:bg-neutral-800"></li>
                        </ul>                
                    </div>
                </div>
            </section>
        </div>
    </section>
    <section aria-label="achievements" class="py-12">
        <div class="px-4 mx-auto max-w-screen-xl">
            <div class="flex items-center justify-between mb-8">
                <h1 class="text-3xl font-extrabold tracking-tight text-gray-900 md:text-4xl dark:text-white">Başarılarımız</h1>
                <a href="achievements" rel="noopener noreferrer" class="inline-flex items-center font-medium underline underline-offset-4 text-black dark:text-gray-300 hover:no-underline">Tümünü gör</a>
            </div>
            <div id="achievementsContent" class="grid grid-cols-2 gap-2">
                <div class="p-8 col-span-2 h-96 bg-gray-200 dark:bg-neutral-800 animate-pulse"></div>
                <div class="p-8 col-span-2 md:col-span-1 h-96 bg-gray-200 dark:bg-neutral-800 animate-pulse"></div>
                <div class="p-8 col-span-2 md:col-span-1 h-96 bg-gray-200 dark:bg-neutral-800 animate-pulse"></div>
            </div>
        </div>
    </section>
</main>