<div class="p-4 pt-10 sm:ml-64">
    <div class="grid grid-cols-1 gap-4 lg:grid-cols-3 mt-20">
        <div class="p-6 bg-white dark:bg-black border border-gray-200 dark:border-gray-600 rounded-lg shadow">
            <p class="mb-2 text-xl font-semibold tracking-tight text-gray-900 dark:text-white">Aktif Akademik Dönem</p>
            <div id="academicYearPre" class="text-sm font-semibold w-24 h-2 bg-gray-300 rounded-full animate-pulse"></div>
            <p id="academicYear" class="text-sm font-semibold text-gray-700 dark:text-gray-400 hidden"></p>
        </div>
            <div class="p-6 bg-white dark:bg-black border border-gray-200 dark:border-gray-600 rounded-lg shadow">
            <p class="mb-2 text-xl font-semibold tracking-tight text-gray-900 dark:text-white">Danışman Bilgileri</p>
            <div id="advisorPre" class="mb-1 text-sm font-semibold w-24 h-2 bg-gray-300 rounded-full animate-pulse"></div>
            <div id="advisorPre" class="text-sm font-semibold w-16 h-2 bg-gray-300 rounded-full animate-pulse"></div>
            <p id="advisor" class="mb-1 text-sm font-semibold text-gray-700 dark:text-gray-400" style="display: none;"></p>
        </div>
        <div class="p-6 bg-white dark:bg-black border border-gray-200 dark:border-gray-600 rounded-lg shadow">
            <p class="mb-2 text-xl font-semibold tracking-tight text-gray-900 dark:text-white">Öğrenim Bilgileri</p>
            <div id="programPre" class="mb-1 text-sm font-semibold w-48 h-2 bg-gray-300 rounded-full animate-pulse"></div>
            <div id="programPre" class="mb-1 text-sm font-semibold w-28 h-2 bg-gray-300 rounded-full animate-pulse"></div>
            <p id="unitName" class="mb-1 text-sm font-semibold text-gray-700 dark:text-gray-400" style="display: none;"></p>
            <p id="programName" class="mb-1 text-sm font-semibold text-gray-700 dark:text-gray-400" style="display: none;"></p>
            <span id="programDetail"class="text-xs font-semibold underline cursor-pointer text-blue-500" style="display: none;">Detay ></span>
        </div>
    </div>
    <?= var_dump($_SESSION); ?>
</div>
