<main class="mt-20 lg:mt-24">
    <section class="w-full h-64 bg-no-repeat bg-cover bg-center relative border-b border-gray-700" style="background-image: url('assets/static/img/ebbb311c-1696-44ac-838a-6194dd216016.webp');">
        <div class="absolute top-20 left-1/2 px-4 mx-auto w-full max-w-screen-xl -translate-x-1/2 xl:top-1/2 xl:-translate-y-1/2 xl:px-0">
            <h1 class="max-w-4xl text-3xl font-extrabold text-white"><?= $element['pageTitle'] ?? 'Error'; ?></h1>
        </div>
    </section>
    <section class="flex relative z-20 min-h-96 justify-center px-4 mx-auto max-w-screen-lg">
        <div class="w-full py-6">
            <div class="space-y-4 text-gray-900 dark:text-gray-300 h-full">
                <?= isset($element['postText']) ? manipulateTheElement($element['pageTitle']) : 'Error'; ?>
            </div>
        </div>
    </section>
</main>