<!DOCTYPE html>
<html lang="en" translate="no" class="dark">
<head>
    <!-- Rules -->
    <base href="/">
    <!-- Meta -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="cache-control" content="no-cache">
	<meta name="google" content="notranslate">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="Bu yolda, öğrencilerimizi yalnızca derslere değil, hayata hazırlıyoruz.">
    <meta name="keywords" content="İstanbul Nişantaşı Üniversitesi, NİŞANTAŞI, ÜNİVERSİTESİ, nişantaşı, üniversitesi, istanbul üniversite, Nişantaşı Üniversitesi">
    <meta name="author" content="Misy">
    <!-- OpenGraph -->
    <meta property="og:title" content="İstanbul Nişantaşı Üniversitesi">
    <meta property="og:description" content="Bu yolda, öğrencilerimizi yalnızca derslere değil, hayata hazırlıyoruz." />
    <meta property="og:type" content="article">
    <meta property="og:url" content="https://nisantasi.edu.tr">
    <meta property="og:image" content="assets/static/img/logo.webp">
    <!-- Basic Page Needs -->
    <title>İstanbul Nişantaşı Üniversitesi</title>
    <!-- Favicon -->
    <link rel="apple-touch-icon" type="image/x-icon" sizes="180x180" href="favicon.ico" />
    <link rel="icon" type="image/x-icon" sizes="32x32" href="favicon.ico" />
    <link rel="icon" type="image/x-icon" sizes="16x16" href="favicon.ico" />
    <!-- CSS -->
    <link href="assets/static/css/main-971051bc6c224.css?v=68" rel="stylesheet" type="text/css" />
    <!-- Scripts -->
	<script type="text/javascript">
    if (window.history.replaceState) { window.history.replaceState(null, null, window.location.href); }
    if (localStorage.getItem('color-theme') === 'light') { document.documentElement.classList.remove('dark'); } 
    </script>
    <style>::-webkit-scrollbar{width: 0px;}</style>
    <!--<script src="https://cdn.tailwindcss.com"></script>-->     
</head>
<body class="bg-white dark:bg-black antialiased <?= $_SERVER['REQUEST_URI'] == '/' || $_SERVER['REQUEST_URI'] == '/aday' ? "bg-[url('/assets/static/img/background/69a02caa-248f-43b2-808b-6867e7e24462.svg')] dark:bg-[url('/assets/static/img/background/392a42c3-69f7-4792-abb8-b9e5cc180483.svg')]" : ''; ?>">
<noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript>