<header class="fixed top-0 z-50 w-full">
    <!--<section class="p-2 bg-gray-200 dark:bg-neutral-800">
        <div class="flex justify-between px-4 lg:px- font-medium text-xs lg:text-sm text-gray-600 dark:text-gray-300">
            <a href="tel:+902122101010" class="inline-flex hover:underline">
                +90 (212) 210 10 10
                <svg width="7" viewBox="0 0 6 6" height="7" aria-hidden="true"><path fill="currentColor" d="m1.252 5.547-.63-.63 3.16-3.161H1.383L1.39.891h3.887v3.89h-.87l.005-2.396z"></path></svg>
            </a>            
            <div class="space-x-2">
                <a href="contact" class="hover:underline">İletişim</a>
                <span>|</span>
                <a class="hover:underline">INUnet</a>
                <span>|</span>
                <a href="login" class="hover:underline inline-flex" rel="noopener noreferrer">
                    Oturum Aç
                    <svg width="7" viewBox="0 0 6 6" height="7" aria-hidden="true"><path fill="currentColor" d="m1.252 5.547-.63-.63 3.16-3.161H1.383L1.39.891h3.887v3.89h-.87l.005-2.396z"></path></svg>
                </a>            
            </div>
        </div>
    </section>-->
    <nav class="bg-white border-b border-gray-400 dark:border-neutral-700 dark:bg-black px-4 lg:px-6 py-4">
        <div class="flex flex-wrap justify-between items-center mx-auto">
            <a href="/" rel="noopener noreferrer" aria-hidden="true" tabindex="-1"><?= IncludeAsset('logo'); ?></a>
            <div class="flex items-center lg:order-2 space-x-2">
                <div>
                    <button type="button" aria-hidden="true" tabindex="-1" data-dropdown-toggle="language-dropdown" class="inline-flex justify-center p-2 text-gray-500 rounded cursor-pointer hover:bg-gray-100 dark:hover:bg-neutral-800/80">
                        <svg aria-hidden="true" class="h-5 w-5 rounded-full mt-0.5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 3900 3900"><path fill="#b22234" d="M0 0h7410v3900H0z"/><path d="M0 450h7410m0 600H0m0 600h7410m0 600H0m0 600h7410m0 600H0" stroke="#fff" stroke-width="300"/><path fill="#3c3b6e" d="M0 0h2964v2100H0z"/><g fill="#fff"><g id="d"><g id="c"><g id="e"><g id="b"><path id="a" d="m247 90 70.534 217.082-184.66-134.164h228.253L176.466 307.082z"/><use xlink:href="#a" y="420"/><use xlink:href="#a" y="840"/><use xlink:href="#a" y="1260"/></g><use xlink:href="#a" y="1680"/></g><use xlink:href="#b" x="247" y="210"/></g><use xlink:href="#c" x="494"/></g><use xlink:href="#d" x="988"/><use xlink:href="#c" x="1976"/><use xlink:href="#e" x="2470"/></g></svg>
                    </button>
                    <div class="hidden z-50 my-4 text-base list-none bg-white rounded dark:bg-neutral-800 shadow" id="language-dropdown">
                        <ul class="py-1" role="none">
                            <li>
                                <a href="#" class="block py-2 px-4 text-sm text-gray-900 dark:text-gray-400 hover:text-gray-500 dark:hover:text-gray-300" role="menuitem">
                                    <div class="inline-flex items-center">English (US)</div>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="block py-2 px-4 text-sm text-gray-900 dark:text-gray-400 hover:text-gray-500 dark:hover:text-gray-300" role="menuitem">
                                    <div class="inline-flex items-center">English (US)</div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div>
                    <button id="theme-toggle" aria-hidden="true" tabindex="-1" type="button" class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-neutral-800/80 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
                        <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 0 1 6.707 2.707a8.001 8.001 0 1 0 10.586 10.586"/></svg>
                        <svg id="theme-toggle-light-icon" class="hidden h-5 w-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
                    </button>
                </div>
                <div class="lg:hidden" data-collapse-toggle="header-menu">
                    <button aria-hidden="true" tabindex="-1" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg hover:bg-gray-100 dark:hover:bg-neutral-800/80" aria-controls="header-menu" aria-expanded="false">
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1m0 5a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1m0 5a1 1 0 0 1 1-1h12a1 1 0 1 1 0 2H4a1 1 0 0 1-1-1" clip-rule="evenodd"/></svg>                
                    </button>
                </div>
            </div>
            <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="header-menu">
                <ul id="headerMenuContent" class="flex flex-col mt-4 font-medium gap-1 lg:flex-row lg:space-x-8 lg:mt-0">
                    <li>
                        <span class="block w-16 h-2 bg-gray-300 dark:bg-neutral-800 rounded-full animate-pulse"></span>
                    </li>
                    <li>
                        <span class="block w-16 h-2 bg-gray-300 dark:bg-neutral-800 rounded-full animate-pulse"></span>
                    </li>
                    <li>
                        <span class="block w-16 h-2 bg-gray-300 dark:bg-neutral-800 rounded-full animate-pulse"></span>
                    </li>
                    <li>
                        <span class="block w-16 h-2 bg-gray-300 dark:bg-neutral-800 rounded-full animate-pulse"></span>
                    </li>
                    <li>
                        <span class="block w-16 h-2 bg-gray-300 dark:bg-neutral-800 rounded-full animate-pulse"></span>
                    </li>
                    <li>
                        <span class="block w-16 h-2 bg-gray-300 dark:bg-neutral-800 rounded-full animate-pulse"></span>
                    </li>
                    <li>
                        <span class="block w-16 h-2 bg-gray-300 dark:bg-neutral-800 rounded-full animate-pulse"></span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>