<!DOCTYPE html>
<html lang="en" translate="no" class="dark">
<head>
    <!-- Meta -->
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta http-equiv="cache-control" content="max-age=604800">
	<meta name="google" content="notranslate">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Misy">
    <meta name="keywords" content="Misy">
    <meta name="author" content="Misy">
    <base href="/">
    <!-- Basic Page Needs -->
    <title>İstanbul Nişantaşı Üniversitesi - Yönetim Paneli</title>
    <!-- Favicon -->
    <link rel="apple-touch-icon" type="image/webp" sizes="180x180" href="assets/img/favicon.webp">
    <link rel="icon" type="image/webp" sizes="32x32" href="assets/img/favicon.webp">
    <link rel="icon" type="image/webp" sizes="16x16" href="assets/img/favicon.webp">
    <!-- CSS -->
    <link href="assets/static/css/main-971051bc6c224.css?v=61" rel="stylesheet" type="text/css" />
    <!-- Scripts -->
	<script type="text/javascript">
    if(window.history.replaceState){window.history.replaceState(null, null, window.location.href);}
    if(localStorage.getItem('color-theme') === 'light') { document.documentElement.classList.remove('dark') } 
    </script>
    <style>::-webkit-scrollbar{width: 0px;}</style>
    <!--<script src="https://cdn.tailwindcss.com"></script>-->     
</head>
<body class="bg-gray-100 dark:bg-neutral-900 antialiased">
<noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript>